AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless application with producer Lambda function

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project
  FunctionName:
    Type: String
    Description: Name of the producer Lambda function
  LambdaExecutionRoleArn:
    Type: String
    Description: ARN of the existing IAM role for the producer Lambda execution
  
  QueueUrl:
    Type: AWS::SSM::Parameter::Value<String>
    Description: URL of the existing SQS queue
    Default: /sqs/oslo/queue-url
  AllowedIps:
    Type: AWS::SSM::Parameter::Value<List<String>>
    Description: Comma-separated list of allowed IP addresses for the producer Lambda function
    Default: /allowed-ips/all
  AllowedClientId:
    Type: AWS::SSM::Parameter::Value<String>
    Description: JWT sub claim value of the single allowed client
    Default: /projects/helsinki/allowed-client-id
  AllowedClientSecret:
    Type: AWS::SSM::Parameter::Value<String>
    Description: JWT secret of the single allowed client
    Default: /projects/helsinki/allowed-client-secret
  JwtSigningSecret:
    Type: AWS::SSM::Parameter::Value<String>
    Description: JWT signing secret for the producer Lambda function
    Default: /projects/helsinki/jwt-signing-secret

Outputs:
  FunctionArn:
    Description: ARN of the producer Lambda function
    Value: !GetAtt Function.Arn

  FunctionName:
    Description: Name of the producer Lambda function
    Value: !Ref FunctionName

  ApiGatewayUrl:
    Description: URL of the API Gateway endpoint
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/"

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: REGIONAL
      Auth:
        ResourcePolicy:
          CustomStatements:
            # - Effect: Allow
            #   Principal: "*"
            #   Action: execute-api:Invoke
            #   Resource: "arn:aws:execute-api:*:*:*/*/*/*"
            - Effect: Deny
              Principal: "*"
              Action: execute-api:Invoke
              Resource: "arn:aws:execute-api:*:*:*/*/*/*"
              Condition:
                NotIpAddress:
                  aws:SourceIp: !Ref AllowedIps
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref FunctionName
      Runtime: python3.14
      Handler: app.main.lambda_handler
      CodeUri: lambda.zip
      Role: !Ref LambdaExecutionRoleArn
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: !Ref FunctionName
          POWERTOOLS_LOG_LEVEL: INFO
          QUEUE_URL: !Ref QueueUrl
          ALLOWED_CLIENT_ID: !Ref AllowedClientId
          ALLOWED_CLIENT_SECRET: !Ref AllowedClientSecret
          JWT_SIGNING_SECRET: !Ref JwtSigningSecret
      Tags:
        Project: !Ref ProjectName
        Name: !Ref FunctionName
      Events:
        ApiEventRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /
            Method: ANY
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{proxy+}
            Method: ANY

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${FunctionName}"
      RetentionInDays: 30
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Name
          Value: !Sub "/aws/lambda/${FunctionName}"

